//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insertGuaXingtoPowerpnt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("insertGuaXingtoPowerpnt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64卦圖
        ///行書
        ///
        ///小篆
        ///甲骨文
        ///金文
        ///隸書
        ///文鼎隸書B
        ///文鼎隸書DB
        ///文鼎隸書HKM
        ///文鼎隸書M
        ///
        ///華康行書體
        ///文鼎行楷L
        ///DFGGyoSho-W7
        ///DFPGyoSho-W7
        ///
        ///文鼎魏碑B
        ///文鼎行楷碑體B
        ///Hanyi Senty Floral Calligraphy
        ///Hanyi Senty Lingfei Scroll
        ///漢儀新蒂語文體
        ///漢儀新蒂語文體430size
        ///文鼎鋼筆行楷M
        ///DFPOYoJun-W5
        ///DFPPenJi-W4
        ///
        ///
        ///FangSong
        ///Adobe仿宋StdR
        ///文鼎仿宋B
        ///文鼎仿宋L
        ///
        ///教育部標準楷書
        ///Adobe楷体StdR
        ///KaiTi
        ///文鼎標準楷體ProM
        ///
        ///文鼎顏楷H
        ///文鼎顏楷U
        ///文鼎毛楷B
        ///文鼎毛楷EB
        ///文鼎毛楷H
        ///
        ///DFMinchoP-W5
        ///
        ///DFGothicP-W5
        ///
        ///DFGKanTeiRyu-W11
        ///文鼎古印體B
        ///漢儀新蒂佛塔書
        ///漢儀新蒂牌樓體
        ///
        ///文鼎雕刻體B
        ///DFKinBun-W3
        ///DFPGiHi-W7
        ///
        ///DFGFuun-W7
        ///
        ///::華康行書體(P)以下為沒必要做的 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fontOkList {
            get {
                return ResourceManager.GetString("fontOkList", resourceCulture);
            }
        }
    }
}
