//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace insertGuaXingtoPowerpnt.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("insertGuaXingtoPowerpnt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 //「//」符註明各字型之分類，及其他註記用。首見之雙「:」符則作為字圖與識別不必做或無法做之字圖之區隔。
        ///64卦圖
        ///8卦圖
        ///行書
        ///
        ///小篆
        ///甲骨文
        ///金文
        ///隸書
        ///文鼎隸書B
        ///文鼎隸書DB
        ///文鼎隸書HKM
        ///文鼎隸書M
        ///華康隸書體W3
        ///華康隸書體W3(P)
        ///華康隸書體W5
        ///華康隸書體W5(P)
        ///華康隸書體W7
        ///華康隸書體W7(P)
        ///華康隸書體 Std W3
        ///華康隸書體 Std W5
        ///華康隸書體 Std W7
        ///華康唐風隸
        ///華康唐風隸(P)
        ///華康唐風隸W5
        ///華康唐風隸W5(P)
        ///華康唐風隸W7
        ///華康唐風隸W7(P)
        ///華康唐風隸 Std W5
        ///華康唐風隸 Std W7
        ///華康唐風隸 Std W9
        ///華康新篆體
        ///華康新篆體(P)
        ///華康新篆體 Std W5
        ///華康行書體
        ///文鼎行楷L
        ///文鼎行楷B
        ///文鼎行書M
        ///華康行楷體W5
        ///華康行楷體W5(P)
        ///DFGGyoSho-W7
        ///DFPGyoSho-W7
        ///DFGPenJi-W4
        ///
        ///
        ///
        /////風格體
        ///文鼎魏碑B
        ///華康魏碑體
        ///華康魏碑體(P)
        ///華康魏碑體 Std W7
        ///文鼎行楷碑體B
        ///DFPWe [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string fontOkList {
            get {
                return ResourceManager.GetString("fontOkList", resourceCulture);
            }
        }
    }
}
